### ISSUE TITLE
TK45 - Crear Componente Receta

### ISSUE THREAD

**Issue by FlorenciaItati** [Nervios-de-Acero/Avocado-Frontend#12]
Tarea: Desarrollar un componente de receta en Angular que representa cada tarjeta de receta dentro del feed. Cada tarjeta de receta contendrá una imagen de la receta, su título y una descripción breve.
Criterios de aceptación:
Se debe crear un componente de Angular llamado "Receta".
El componente de receta debe incluir una imagen de la receta, su título y una descripción breve.
La imagen de la receta debe ser proporcionada dinámicamente desde la base de datos o mediante una URL externa.
El título y la descripción de la receta deben ser proporcionados dinámicamente desde la base de datos.
El diseño de la tarjeta de receta debe ser atractivo y fácil de leer.

_Ejemplo de uso:_
En el componente de feed, cada tarjeta de receta será representada por el componente de receta.
Cada tarjeta de receta mostrará una imagen de la receta, su título y una breve descripción.
Los usuarios podrán desplazarse por el feed y ver las diferentes tarjetas de receta, cada una con su propia imagen, título y descripción.
Caso de uso: Exploración de Recetas en el Feed
Dado que: Los usuarios desean explorar diferentes recetas disponibles en el feed.
Cuando: Accedan al componente de feed.
Entonces: Los usuarios podrán desplazarse por las tarjetas de receta, cada una con una imagen, un título y una descripción, para encontrar recetas de su interés.

**Comment by FlorenciaItati** [comment]
SubTK45 - Maquetación componente receta

**Comment by FlorenciaItati** [comment]
SubTK45 - Maquetación vista detallada receta

**Comment by GastonSca** [comment]
SubTK45 - Logica  vista detallada receta
