### ISSUE TITLE
TK42 - Crear Componente de Registro (form registro)

### ISSUE THREAD

**Issue by Yanina-Unrein** [Nervios-de-Acero/Avocado-Frontend#2]
**Tarea:** Desarrollar un componente de registro que permita a los usuarios registrarse en la aplicación web y los redirija a la página de inicio después de un registro exitoso. Además, serán implementadas validaciones para detectar errores en los campos del formulario.

**Criterios de aceptación:**
Se debe crear un componente de Angular llamado "Registro".
El componente debe incluir un formulario de registro con campos para ingresar información requerida, como nombre, dirección de correo electrónico, contraseña, etc.
Se debe implementar la lógica necesaria para enviar los datos del formulario al servidor y realizar el registro del usuario.
Después de un registro exitoso, será notificado del mismo, el usuario debe ser redirigido automáticamente a la página de inicio de sesión.
Se deben implementar validaciones en el formulario para detectar errores en los campos, como campos vacíos o formatos incorrectos de correo electrónico.
El diseño y la interfaz de usuario del componente deben seguir las pautas de diseño establecidas para la aplicación.
Ejemplo de uso:
Al acceder al componente de registro, los usuarios podrán completar el formulario con la información requerida para registrarse en la aplicación.
Después de un registro exitoso, el usuario será redirigido automáticamente a la página de inicio de sesión, donde podrá ingresar con las credenciales recién registradas.
Si se detecta algún error en los campos del formulario, se mostrarán mensajes de error para guiar al usuario sobre cómo corregir los problemas antes de enviar el formulario.

**Caso de uso: Registro de Usuario**
Dado que: Los usuarios necesitan registrarse para acceder a la aplicación.
Cuando: Se acceda al formulario de registro.
Entonces: Los usuarios podrán completar el formulario y registrarse en la aplicación, siendo redirigidos automáticamente a la página de inicio después de un registro exitoso.

____________________________________________________________________________________________________________________________________________

- Relacionada a:
- Es bloqueado por:

**Comment by Yanina-Unrein** [comment]
SubTK42 - Maquetación del componente Registrarse

**Comment by GastonSca** [comment]
SubTK42 - Lógica del componente Registrarse
