### ISSUE TITLE
TK43 - Crear Componente Perfil

### ISSUE THREAD

**Issue by GastonSca** [Nervios-de-Acero/Avocado-Frontend#4]
Tarea: Desarrollar un componente de perfil que permita a los usuarios ver, editar y eliminar su perfil. El componente debe mostrar la foto de perfil del usuario, así como los datos como correo electrónico y contraseña, y permitir la edición de estos campos con la posibilidad de guardar los cambios realizados.

Criterios de aceptación:
Se debe crear un componente de Angular llamado "Perfil".
El componente debe mostrar la foto de perfil del usuario, así como los datos como correo electrónico y contraseña.
Se debe implementar la lógica necesaria para recuperar los datos del perfil del usuario y mostrarlos en el componente.
Se debe proporcionar funcionalidad para editar los campos del perfil, incluyendo la foto de perfil, el correo electrónico y la contraseña.
Después de realizar cambios en el perfil, se debe permitir al usuario guardar los cambios para actualizar la información en el servidor.
Se debe proporcionar la opción de eliminar el perfil del usuario, lo que resultará en la eliminación permanente de los datos asociados.

Ejemplo de uso:
Al acceder al componente de perfil, los usuarios podrán ver su foto de perfil, así como los datos como correo electrónico y contraseña asociados a su cuenta.
Se proporcionará la opción de editar cada campo del perfil, lo que permitirá al usuario modificar la información según sea necesario.
Después de realizar cambios en el perfil, se permitirá al usuario guardar los cambios para actualizar la información en el servidor.
Además, se proporcionará la opción de eliminar el perfil del usuario, lo que resultará en la eliminación permanente de los datos asociados.

Caso de uso: Gestión del Perfil de Usuario
Dado que: Los usuarios necesitan gestionar su perfil dentro de la aplicación.
Cuando: Accedan al componente de perfil.
Entonces: Los usuarios podrán ver, editar y eliminar su perfil, con la opción de guardar los cambios realizados.

____________________________________________________________________________________________________________________________________________

- Relacionada a:
- Es bloqueado por:

**Comment by GastonSca** [comment]
SubTK43 - Lógica Componente Perfil

**Comment by Yanina-Unrein** [comment]
SubTK43 - Maquetación Componente Perfil
